Libraries

In [1]:
import pandas as pd
import numpy as np

import requests
from bs4 import BeautifulSoup

import re

import utils as lf

In [3]:
lf.get_table('2liga')

,Poz,Zespół,Mecze_rozegrane,Pkt.,Pkt.,Z,R,P,BZ,BS,+/-,Forma
0,1,Husaria Mokotów,8,1,21,7,0,1,70,20,50,"W,W,P,W,W"
1,2,Dziki Młochów,8,2,18,6,0,2,53,35,18,"W,W,W,P,W"
2,3,UEFA Mafia Ursynów,8,3,15,5,0,3,48,38,10,"W,W,W,W,W"
3,4,KSB Warszawa,8,4,15,5,0,3,68,49,19,"W,W,P,P,P"
4,5,Orzeły Stolicy,8,5,13,4,1,3,33,26,7,"P,P,P,W,W"
5,6,AFC Goodfellas,8,6,10,3,1,4,37,47,-10,"W,W,P,W,P"
6,7,Green Lantern,8,7,9,3,0,5,43,58,-15,"P,P,W,P,W"
7,8,Tylko Zwycięstwo,8,8,9,3,0,5,28,47,-19,"P,P,W,W,P"
8,9,Warszawska Ferajna,8,9,6,2,0,6,22,61,-39,"P,P,W,P,P"
9,10,Korsarze,8,10,2,1,0,7,27,48,-21,"P,P,P,P,P"

In [3]:
# Index improvement needed
lf.get_matches('2liga', round_=7)

,Kol.,Data,Godz.,Gospodarz,,Gość,Video,,Sędzia,Boisko,Raport
2,7,2023-11-12,09:00,Dziki Młochów,7 : 4,Tylko Zwycięstwo,,,Volodymyr Molokov,Arena AWF,Raport
2,7,2023-11-12,14:00,Orzeły Stolicy,3 : 5,Husaria Mokotów,,,Volodymyr Molokov,Arena AWF,Raport
2,7,2023-11-12,17:00,Korsarze,3 : 8,AFC Goodfellas,,,Volodymyr Molokov,Arena AWF,Raport
2,7,2023-11-12,19:00,UEFA Mafia Ursynów,8 : 2,Warszawska Ferajna,,,Piotr Krajczyński,Arena AWF,Raport
2,7,2023-11-12,19:00,Green Lantern,6 : 18,KSB Warszawa,,,Rafał Szczytniewski,Arena AWF,Raport

In [5]:
lf.get_squad_details('8liga', 'Kozice Warszawa')

,Imie i nazwisko,Numer,Liczba wystepów,Liczba bramek,Asysty,Kanadyjcztk,Superstar,Top6,MVP,Czerwone kartki,Zółte kartki,Stracone bramki,Samobój,Obronione karne,Czyste konto,Gold Team,ID
0,Krzysztof Wiśniewski,,8,0,0,0,2,0,0,0,0,43,0,0,0,0,7698
1,Hubert Kielak,,0,0,0,0,0,0,0,0,0,0,0,0,0,0,7697
2,Ahmad Tijjani Bala,,2,0,0,0,0,0,0,0,1,0,0,0,0,0,9815
3,Kacper Osica,,1,0,0,0,0,0,0,0,0,0,0,0,0,0,9724
4,Wojtek Soból,,0,0,0,0,0,0,0,0,0,0,0,0,0,0,7704
5,Robert Afifi,,6,2,1,3,0,1,0,0,0,0,0,0,0,0,7702
6,Patryk Cytryna,,8,2,1,3,0,0,0,0,0,0,0,0,0,0,9431
7,Krystian Kielak,,0,0,0,0,0,0,0,0,0,0,0,0,0,0,7700
8,Kamil Faryniarz,,7,1,6,7,0,0,0,0,1,0,0,0,0,0,7699
9,Kacper Napora,,5,14,6,20,8,2,1,0,0,0,0,0,0,0,7696
10,Kajetan Kossakowski,,4,0,0,0,0,0,0,0,0,0,0,0,0,0,7694
11,Rafał Kruk,,2,0,0,0,0,0,0,0,0,0,0,0,0,0,7695
12,Kuba Rogoyski,,1,0,0,0,0,0,0,0,0,0,0,0,0,0,9432
13,Igor Nowak,,1,0,0,0,0,0,0,0,0,0,0,0,0,0,3900
14,Kuba Wieteska,,7,3,1,4,0,0,0,0,3,0,0,0,0,0,8400
15,Debal Bose,,1,0,1,1,0,0,0,0,0,0,0,0,0,0,8552
16,Alli Abdullahi,,6,5,3,8,2,1,0,0,0,0,0,0,0,0,8399
17,Kuba Gadomski,,0,0,0,0,0,0,0,0,0,0,0,0,0,0,8401
18,Mariusz Grzybowski,,6,0,0,0,0,0,0,0,1,0,0,0,0,0,3314
19,Michał Szeniawski,,6,1,2,3,0,0,0,0,0,0,0,0,0,0,2721
20,Valentine Chekwube,,8,12,5,17,4,1,0,0,0,0,0,0,0,0,8162
21,Radek Rząd,,0,0,0,0,0,0,0,0,0,0,0,0,0,0,9430
22,Rafał Słodownik,,0,0,0,0,0,0,0,0,0,0,0,0,0,0,8062
23,Rafał Woźnica,,5,0,0,0,0,0,0,0,0,0,0,0,0,0,8217

# Working area

In [2]:
lf.ligi

{'ekstraklasa': 'https://ligafanow.pl/rozgrywki/tabela/30/235',
 '1liga': 'https://ligafanow.pl/rozgrywki/tabela/30/234',
 '2liga': 'https://ligafanow.pl/rozgrywki/tabela/30/231',
 '3liga': 'https://ligafanow.pl/rozgrywki/tabela/30/232',
 '4liga': 'https://ligafanow.pl/rozgrywki/tabela/30/233',
 '5liga': 'https://ligafanow.pl/rozgrywki/tabela/30/230',
 '6liga': 'https://ligafanow.pl/rozgrywki/tabela/30/229',
 '7liga': 'https://ligafanow.pl/rozgrywki/tabela/30/228',
 '8liga': 'https://ligafanow.pl/rozgrywki/tabela/30/227',
 '9liga': 'https://ligafanow.pl/rozgrywki/tabela/30/226',
 '10liga': 'https://ligafanow.pl/rozgrywki/tabela/30/225',
 '11liga': 'https://ligafanow.pl/rozgrywki/tabela/30/224',
 '12liga': 'https://ligafanow.pl/rozgrywki/tabela/30/223',
 '13liga': 'https://ligafanow.pl/rozgrywki/tabela/30/236'}

In [113]:
# Obecny etap prac

In [ ]:
# Wyświetlanie rezultatu

In [2]:
def match_result(path):
    response = requests.get(path)

    soup = BeautifulSoup(response.text, 'html.parser')

    # Znajdź wszystkie tabelki na stronie
    tables = soup.find_all('table')
    
    # Znajdź zespoły w title
    title_content = soup.title.string
    
    wynik = re.search(r'\((.*?)\)', title_content)
    wynik = wynik[1].strip()
    matches = re.search(r'\(.*?\)\s*(.+?)\s+vs\s+(.+?)\s+-', title_content)
    matches[1].strip()
    matches[2].strip()
    
    print(f'{matches[1].strip()} vs {matches[2].strip()}: {wynik}')

In [3]:
# Wyświetlanie danych z meczów ze ścieżki

In [4]:
def match_details(path):
    if path != None:
        response = requests.get(path)

        soup = BeautifulSoup(response.text, 'html.parser')

        # Znajdź wszystkie tabelki na stronie
        tables = soup.find_all('table')

        # Znajdź zespoły w title
        title_content = soup.title.string
        matches = re.search(r'\(.*?\)\s*(.+?)\s+vs\s+(.+?)\s+-', title_content)
        if matches:
            team1 = matches[1].strip()
            team2 = matches[2].strip()

        # Przechowaj ramki danych w liście
        dataframes = []

        # Sprawdź, czy znaleziono jakiekolwiek tabele
        if tables:
            # Iteruj przez wszystkie znalezione tabele
            for table in tables:
                # Wydziel dane z tabeli do listy słowników
                table_data = []
                rows = table.find_all('tr')

                # Sprawdź, czy istnieje przynajmniej jeden wiersz
                if rows:
                    header = [header.text.strip() for header in rows[0].find_all(['th', 'td'])]

                    # Iteruj przez pozostałe wiersze
                    for row in rows[1:]:
                        row_data = [cell.text.strip() for cell in row.find_all(['th', 'td'])]
                        table_data.append(dict(zip(header, row_data)))

                    # Przekształć dane do DataFrame
                    df = pd.DataFrame(table_data)
                    dataframes.append(df)

        # Wydrukuj ramki danych
        tab1 = dataframes[1]
        tab1['Zespół'] = team1
        tab2 = dataframes[2]
        tab2['Zespół'] = team2

        df = pd.concat([tab1,tab2]).dropna()
    else:
        df = None
    return df

#### Funkcja zwracająca tabelę z linkami do konkretnych kolejek - należy jeszcze zaprogramować wyszukiwanie po rywalach i w przyszłości rozróżnienie na kolejkę jesienną i zimową

In [26]:
def get_matches_links(league, team):
    # Inicjalizuj listy, do których będziemy dodawać dane
    links = lf.table_of_links(league)
    link = links.loc[links['Zespół'].str.contains(lf.adjust_team_name(team)), 'Zespół'].iloc[0]
    matches_links = lf.reports_links(link)
    
    links_list = []
    kolejka_list = []
    data_list = []
    godzina_list = []
    wyniki_list = []
    przeciwnicy_list = []

    # Iteruj po linkach
    for link in matches_links:
        # Pobierz zawartość strony
        response = requests.get(link)
        soup = BeautifulSoup(response.text, 'html.parser')

        # Wyszukaj element z informacją o kolejce
        kolejka_element = soup.find('div', class_='BoxHeaderTitle')

        if kolejka_element:
            # Pobierz tekst
            tekst_kolejki = kolejka_element.get_text(strip=True)

            # Użyj wyrażenia regularnego do wyciągnięcia danych
            match = re.match(r"Raport   - Kolejka (\d+), (\d{4}-\d{2}-\d{2} \d{2}:\d{2})", tekst_kolejki)

            if match:
                numer_kolejki, data_godzina = match.groups()

                # Dodaj dane do odpowiednich list
                links_list.append(link)
                kolejka_list.append(numer_kolejki)
                data_list.append(data_godzina.split()[0])
                godzina_list.append(data_godzina.split()[1])
        
        przeciwnik_element = soup.find_all('h2')
        
        if przeciwnik_element:
            
            wyniki_list.append(przeciwnik_element[1].text.strip())
            # Dodanie przeciwnika
            przeciwnik = next(element for element in [przeciwnik_element[0].text.strip(), przeciwnik_element[2].text.strip()] if element != team)
            przeciwnicy_list.append(przeciwnik)

    # Stwórz DataFrame z zebranych danych
    df = pd.DataFrame({
        'link': links_list,
        'kolejka': kolejka_list,
        'data': data_list,
        'godzina': godzina_list,
        'wynik': wyniki_list,
        'przeciwnik': przeciwnicy_list
    })

    # Wyświetl ostateczną tabelkę
    return df

In [6]:
# Funkcja zwracająca przebieg zadeklarowanego spotkania

In [23]:
def get_match_details(league, team, kolejka=None, opponent = None):
    """
    
    """   
    if ((kolejka == None) & (opponent == None)) == False:
        print('Nie podano kolejki ani przeciwnika')
    elif kolejka != None:
        matches = get_matches_links(league, team)
        link = matches[matches.kolejka == str(kolejka)].link.iloc[0]
    elif opponent != None:
        matches = get_matches_links(league, team)
        link = matches[matches['przeciwnik'].str.upper().eq(str(opponent).upper())].link.iloc[0]
    else:
        link = None
    return match_details(link)

In [9]:
str('Kozice').upper()

'KOZICE'

In [ ]:
# Dokładanie rywala

In [ ]:
link, rywal, kolejka, data, godzina

In [ ]:
# Dokładanie kolejki

In [3]:
league = '8liga'
team = 'Kozice Warszawa'
kolejka = 5
opponent = 'Na2NÓŻKĘ'

In [3]:
matches = lf.get_matches_links(league, team)

In [4]:
matches

,link,kolejka,data,godzina,wynik,przeciwnik:
0,https://ligafanow.pl//statystyki/raport/7919,4,2023-10-15,16:30,2 : 8,Hiszpański Galeon
1,https://ligafanow.pl//statystyki/raport/7845,3,2023-10-08,18:00,7 : 6,FC Polska Górom
2,https://ligafanow.pl//statystyki/raport/7756,2,2023-10-01,13:00,5 : 2,Saska Kępa
3,https://ligafanow.pl//statystyki/raport/8129,6,2023-11-05,11:00,5 : 5,Shot DJ
4,https://ligafanow.pl//statystyki/raport/7682,1,2023-09-24,10:00,4 : 7,Warsaw Gunners FC
5,https://ligafanow.pl//statystyki/raport/8057,5,2023-10-29,12:00,6 : 5,Na2Nóżkę
6,https://ligafanow.pl//statystyki/raport/8271,8,2023-11-19,14:00,:,Mareckie Wygi
7,https://ligafanow.pl//statystyki/raport/8199,7,2023-11-12,15:00,2 : 5,Legion
8,https://ligafanow.pl//statystyki/raport/7990,9,2023-11-26,12:00,7 : 7,BRD Young Warriors

In [18]:
def reports_links(url):
    list_ = extract_mecze_details_links(extract_mecze_links(url)) #dff.Zespół[0])
    list_ = ['https://ligafanow.pl/'+ elem for elem in list_]
    return list_

In [16]:
league='8liga'
links = lf.table_of_links(league)

In [50]:
b = lf.reports_links(links.Zespół[0])
b

['https://ligafanow.pl//statystyki/raport/7919',
 'https://ligafanow.pl//statystyki/raport/7844',
 'https://ligafanow.pl//statystyki/raport/8130',
 'https://ligafanow.pl//statystyki/raport/8198',
 'https://ligafanow.pl//statystyki/raport/8058',
 'https://ligafanow.pl//statystyki/raport/8272',
 'https://ligafanow.pl//statystyki/raport/7754',
 'https://ligafanow.pl//statystyki/raport/7989',
 'https://ligafanow.pl//statystyki/raport/7683']

In [1]:
# Strzelcy

---------------------------------------------------------------------

In [25]:
# Pola do zrobienia z nich tabel

In [123]:
df.Forma[2]

'W 2023-11-12 21:00    In Plus & Pojemna Halina    5 : 7  Gladiatorzy Eternis    Arena AWF  W 2023-11-05 19:00    Gladiatorzy Eternis   14 : 2    ALPAN     Arena AWFR 2023-10-29 18:00    EXC Mobile Ochota   4 : 4  Gladiatorzy Eternis    Arena AWF  W 2023-11-26 18:00    TUR Ochota    1 : 3  Gladiatorzy Eternis    Arena AWF  W 2023-10-15 20:00    Gladiatorzy Eternis   14 : 4    Esportivo Varsovia     Arena AWF'

In [124]:
# zapisanie zmiennej tekstowej do zrobienia z niej tabeli
data = df.Forma[2]

In [125]:
# Prawdziwy kod

In [126]:
# Podzielenie danych na wiersze
rows = re.split(r'([PWR])\s+(\d{4}-\d{2}-\d{2} \d{2}:\d{2})', data)[1:]

In [129]:

# Utwórz DataFrame
columns = ["Typ", "Data", "Czas", "Drużyna 1", "Wynik", "Drużyna 2", "Arena"]
df = pd.DataFrame([row.split()[0:3] + [rozdziel_na_podteksty(row)[1]] + [rozdziel_na_podteksty(row)[2]]+ [rozdziel_na_podteksty(row)[3]] + [rozdziel_na_podteksty(row)[4]] for row in triple_strings(rows)], columns=columns)

In [131]:
df

,Typ,Data,Czas,Drużyna 1,Wynik,Drużyna 2,Arena
0,W,2023-11-12,21:00,In Plus & Pojemna Halina,5 : 7,Gladiatorzy Eternis,Arena AWF
1,W,2023-11-05,19:00,Gladiatorzy Eternis,14 : 2,ALPAN,Arena AWF
2,R,2023-10-29,18:00,EXC Mobile Ochota,4 : 4,Gladiatorzy Eternis,Arena AWF
3,W,2023-11-26,18:00,TUR Ochota,1 : 3,Gladiatorzy Eternis,Arena AWF
4,W,2023-10-15,20:00,Gladiatorzy Eternis,14 : 4,Esportivo Varsovia,Arena AWF